/* eslint max-len: [2, 1000, 4] */

module.exports = [{
  type: 'title',
  text: 'Rejuvenation',
  className: '',
}, {
  type: 'image',
  src: '/images/servicios/tratamientos-dermatologicos/01_rejuvenecimiento.jpg',
  text: 'Rejuvenation',
}, {
  type: 'text',
  className: '',
  text: 'Aging is a normal process of living things in which there is a progressive deterioration determined by our genetics, the passage of time and the damage accumulated by exposure to various factors such as the ultraviolet rays of the sun. The changes are varied and there are different treatment options to address each one of these changes. Depending on the needs of each patient, we help them choose the most suitable treatments to combat the changes generated by the passage of time.',
}, {
  type: 'text',
  className: 'regularMargin',
  text: 'Click on the links below to learn more about our rejuvenating treatments and their functions:',
}, {
  type: 'list_link',
  className: '',
  items: [{
    title: 'Treatment 360',
    href: 'services/cosmetic-dermatology/360-treatment',
  }, {
    title: 'Fractionated Erbium Laser',
    href: '/services/cosmetic-dermatology/fractionated-erbium-laser',
  }, {
    title: 'Fractional Co2 Laser',
    href: '/services/cosmetic-dermatology/laser-co2-fractionated',
  }, {
    title: 'Radiofrequency',
    href: '/services/cosmetic-dermatology/radiofrequency',
  }, {
    title: 'IPL',
    href: '/services/cosmetic-dermatology/ipl-vasculight',
  }, {
    title: 'Dermal Fillers',
    href: '/services/cosmetic-dermatology/dermal-fillers',
  }, {
    title: 'Liquid Face Lift',
    href: '/services/cosmetic-dermatology/liquid-face-lift',
  }, {
    title: 'Botulinum toxin',
    href: '/services/cosmetic-dermatology/botulinum-toxin',
  }, {
    title: 'Facials',
    href: '/services/cosmetic-dermatology/facials',
  }, {
    title: 'Chemical Peeling',
    href: '/services/cosmetic-dermatology/chemical-peel',
  }, {
    title: 'Platelet Rich Plasma',
    href: '/services/cosmetic-dermatology/rich-platelet-plasma',
  }, {
    title: 'Nanopore Turbo Roller',
    href: '/services/cosmetic-dermatology/nanopore-turbo-roller',
  }],
}, {
  type: 'link',
  className: 'btn7green',
  text: 'SCHEDULE APPOINTMENT',
  href: '/contact/rejuvenation',
}];
